site_name: Radxa Zero 3W Docs
site_url: https://aidenpearce1918.github.io/radxa-zero3w-yocto-guide/
repo_url: https://github.com/aidenpearce1918/radxa-zero3w-yocto-guide
repo_name: aidenpearce1918/radxa-zero3w-yocto-guide
theme:
  name: material
  palette:
    - scheme: slate
      primary: cyan
      accent: lime
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.highlight
    - content.code.line_numbers
    - content.code.copy
    - content.code.fold
    - content.code.select
    - content.code.snippet
    - content.code.syntax
    - content.code.wrap
    - content.code.zoom
    - content.code.expand
    - content.code.collapse
    - content.code.toggle
    - content.code.inline
    - content.code.block
    - content.code.inline_block
    - content.code.block_inline
    - content.code.block_expand
    - content.code.block_collapse
    - content.code.block_toggle
    - content.code.block_inline_expand
    - content.code.block_inline_collapse
    - content.code.block_inline_toggle
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line_numbers
    - content.code.block_inline_copy
    - content.code.block_inline_fold
    - content.code.block_inline_highlight
    - content.code.block_inline_annotate
    - content.code.block_inline_zoom
    - content.code.block_inline_wrap
    - content.code.block_inline_select
    - content.code.block_inline_snippet
    - content.code.block_inline_syntax
    - content.code.block_inline_line0